title: stylekyll
name: stylekyll
company: freelance
baseurl: ""
description: "starter repo to make html, css and javascript templates pretty documented for web designer and backend developer"
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json", "Gemfile", "Gemfile.lock"]
